#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: sidpixel
#=================================================

name: 7621.yml

on:
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - '7621.config'
      - '.github/workflows/7621.yml'

  schedule:
    - cron: 23 1 15 */1 *
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  #REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 7621.config
  OS_ARCH: 7621
  #DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name:  Space cleanup and Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff /mnt/swapfile
        sudo rm -rf /imagegeneration /opt /mnt/swapfile /usr/local/aws* /usr/local/julia* /usr/share/swift* /usr/share/sbt* /usr/local/share/chromium* /usr/local/share/powershell* 
        docker rmi `docker images -q`
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-mark hold grub-efi-amd64-signed
        sudo -E apt update
        sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
        sudo -E apt -y full-upgrade
        sudo -E apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
        file wget
        sudo -E systemctl daemon-reload
        sudo -E apt -y autoremove --purge
        sudo -E apt clean
        sudo -E timedatectl set-timezone "Asia/Shanghai"
    - name: Clone source code
      run: |
        df -hT $PWD
        git clone --single-branch  -b $REPO_BRANCH  $REPO_URL openwrt
        chmod +x  $DIY_P2_SH



    - name: Load custom feeds
      working-directory: ./openwrt
      run: |
        $GITHUB_WORKSPACE/$DIY_P2_SH
        mv $GITHUB_WORKSPACE/$FEEDS_CONF feeds.conf.default
        mv $GITHUB_WORKSPACE/$CONFIG_FILE .config
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Download package
      working-directory: ./openwrt
      run: |
        make defconfig
        make download -j$(nproc)

        
    
    - name: Compile the firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) V=s

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Prepare artifact
      run: |
        mkdir -p openwrt/artifact/package
        mkdir -p openwrt/artifact/buildinfo
        rm -rf $(find openwrt/bin/target/ -type d -name "packages")
        cp -rf $(find openwrt/bin/package/ -type f -name "*.ipk") openwrt/artifact/package/
        cp -rf $(find openwrt/bin/target/ -type f -name "*.buildinfo" -o -name "*.manifest") openwrt/artifact/buildinfo/

    - name: Upload buildinfo
      uses: actions/upload-artifact@v3
      with:
        name: OpenWrt_buildinfo
        path: openwrt/artifact/buildinfo/

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: OpenWrt_package
        path: openwrt/artifact/package/

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.OS_ARCH }}-${{ env.FILE_DATE }}
        path: openwrt/artifact/buildinfo/
