#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# License: MIT
# Author: sidpixel
#=================================================

name: 8632.yml

on:
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - '8632.config'
      - 'diy-part2.sh'
      - '.github/workflows/8632.yml'

  schedule:
    - cron: 21 3 1 */1 *

env:
  #REPO_URL: https://github.com/Lienol/openwrt
  REPO_URL: https://github.com/coolsnowwolf/lede
  #REPO_BRANCH: main
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 8632.config
  OS_ARCH: X86_32
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  FORCE_UNSAFE_CONFIGURE: 1


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
        
    - name: Space cleanup and Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo rm -rf /imagegeneration /opt  /usr/local/aws* /usr/local/julia* /usr/share/swift* /usr/share/sbt* /usr/local/share/chromium* /usr/local/share/powershell* 
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch unzip lib32gcc-s1 libc6-dev-i386 subversion flex node-uglify gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils  libelf-dev autoconf automake libtool autopoint device-tree-compiler libuv1-dev python3.6 zlib1g-dev upx-ucl node-uglify antlr3 gperf wget swig rsync
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

    - name: Clone source code
      run: |
        df -hT $PWD
        git clone --single-branch  -b $REPO_BRANCH  $REPO_URL openwrt

    - name: Load custom feeds
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Update feeds
      run: ./openwrt/scripts/feeds update -a

    - name: Install feeds
      run: ./openwrt/scripts/feeds install -a

    - name: Load custom configuration
      run: |
        mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc)

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc)  V=s

    - name: Prepare artifact
      run: |
        mkdir -p openwrt/artifact/package
        mkdir -p openwrt/artifact/buildinfo
        rm -rf $(find openwrt/bin/target/ -type d -name "packages")
        cp -rf $(find openwrt/bin/package/ -type f -name "*.ipk") openwrt/artifact/package/
        cp -rf $(find openwrt/bin/target/ -type f -name "*.buildinfo" -o -name "*.manifest") openwrt/artifact/buildinfo/

    - name: Upload buildinfo
      uses: actions/upload-artifact@v3
      with:
        name: OpenWrt_buildinfo
        path: openwrt/artifact/buildinfo/

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: OpenWrt_package
        path: openwrt/artifact/package/

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.OS_ARCH }}-${{ env.FILE_DATE }}
        path: openwrt/artifact/buildinfo/
