#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# License: MIT
# Author: sidpixel
#=================================================

name: test0.yml

on:
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - '8632.config'
      - '.github/workflows/test0.yml'

  schedule:
    - cron: 21 2 1 */1 *

env:
  REPO_URL: https://github.com/Lienol/openwrt
  #REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: 19.07
  CONFIG_FILE: 8632.config
  OS_ARCH: X86_32
  RELEASE_VERSION: 19.07
  FEEDS_CONF: feeds.conf.default
  READY_SH: ready.sh


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name:  Space cleanup and Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E timedatectl set-timezone "Asia/Shanghai"



    - name: Clone source code
      run: |
        df -hT $PWD
        rm -rf openwrt
        git clone --single-branch  -b $REPO_BRANCH  $REPO_URL openwrt



    - name: generate config file
      working-directory: ./openwrt
      run: |
        mv $GITHUB_WORKSPACE/$CONFIG_FILE  .config
        make defconfig -j$(nproc)

    
  
          

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      run: |     
        grep "CONFIG_LINUX_"  openwrt/.config
        ls -Ahl

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 2
        keep_minimum_runs: 6



 



