#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# License: MIT
# Author: sidpixel
#=================================================

name: test0.yml

on:
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/test0.yml'

  schedule:
    - cron: 21 2 1 */1 *

env:
  REPO_URL: https://github.com/Lienol/openwrt
  #REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: 19.07
  CONFIG_FILE: 8632.config
  OS_ARCH: X86_32
  RELEASE_VERSION: 19.07
  FEEDS_CONF: feeds.conf.default
  READY_SH: ready.sh


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name:  Space cleanup and Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt list|grep urllib2
        sudo -E timedatectl set-timezone "Asia/Shanghai"





 



