#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# License: MIT
# Author: sidpixel
#=================================================

name: test.yml

on:
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/test.yml'

  schedule:
    - cron: 21 2 1 */1 *

env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: 19.07
  CONFIG_FILE: 8632.config
  OS_ARCH: X86_32
  RELEASE_VERSION: 19.07
  FEEDS_CONF: feeds.conf.default
  READY_SH: ready.sh


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name:  Space cleanup and Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        
        
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
       
        sudo -E timedatectl set-timezone "Asia/Shanghai"



    - name: Clone source code
      run: |
        df -hT $PWD
        rm -rf openwrt
        git clone --single-branch  -b $REPO_BRANCH  $REPO_URL openwrt

  

    - name: load the  feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds clean 
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Download package
      working-directory: ./openwrt
      run: |
        make defconfig -j$(nproc)

    

    - name: Organize files
      run: |
        cp openwrt/.config  config8632defult

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: openwrt-firmware
        path:  ./config8632defult



