#=================================================
# https://github.com/sidpixel/lede
# Description: Build OpenWrt using GitHub Actions
# License: MIT
# Author: sidpixel
#=================================================

name: test.yml

on:
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - '8632.config'
      - '.github/workflows/test.yml'

  schedule:
    - cron: 21 2 1 */1 *

env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: 19.07
  CONFIG_FILE: 8632.config
  OS_ARCH: X86_32
  RELEASE_VERSION: 19.07
  FEEDS_CONF: feeds.conf.default
  READY_SH: ready.sh


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name:  Space cleanup and Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E timedatectl set-timezone "Asia/Shanghai"



    - name: Clone source code
      run: |
        df -hT $PWD
        rm -rf openwrt
        git clone --single-branch  -b $REPO_BRANCH  $REPO_URL openwrt


    - name: Load custom feeds and Load custom configuration
      working-directory: ./openwrt
      run: |
        mv $GITHUB_WORKSPACE/$FEEDS_CONF  feeds.conf.default
        bash -x $GITHUB_WORKSPACE/$READY_SH
        cat feeds.conf.default    

    - name: load the  feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds clean 
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Download package
      working-directory: ./openwrt
      run: |
        mv $GITHUB_WORKSPACE/$CONFIG_FILE  .config
        make defconfig -j$(nproc)
        make download -j$(nproc)

    
    - name: Compile the firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) V=s
          

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact
        cp -rf $(find openwrt/bin/targets/*/*/ -name ".config" -o  -name "*.buildinfo" -o -name "*.manifest" -o -name "openwrt*") artifact/
        cd ./artifact/
        gzip --best *
        ls -Ahl

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: openwrt-firmware
        path:  artifact/

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 15
        keep_minimum_runs: 15

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: OpenWRT-${{ env.OS_ARCH }}-${{ env.FILE_DATE }}-${{ env.RELEASE_VERSION }}
        files: artifact/*

